### ISSUE TITLE
no such file or directory error on 'make'

### ISSUE THREAD

**Issue by mr-ice** [mr-ice/maptool-macros#141]
When the 'output' directory does not exist the first 'make' or 'make all' will generate an error.  

When the 'output' directory already exists, running 'make' or 'make all' will run cleanly.

```
~/project/maptool-macros(master) $ make clean
rm -rf *.mtprops *.mtmacro *.mtmacset *.rptok .temp-* output
~/project/maptool-macros(master) $ make all
./dockerrun assemble DNDBeyond+Open5e.project
Traceback (most recent call last):
  File "/usr/local/bin/assemble", line 60, in <module>
    asset.assemble()
  File "/usr/local/bin/asset.py", line 222, in assemble
    return self.assemble_project()
  File "/usr/local/bin/asset.py", line 261, in assemble_project
    asset.assemble()
  File "/usr/local/bin/asset.py", line 224, in assemble
    return self.assemble_properties()
  File "/usr/local/bin/asset.py", line 275, in assemble_properties
    zf = zipfile.ZipFile(self.output_filename, 'w')
  File "/usr/lib/python3.8/zipfile.py", line 1250, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: 'output/DND5e.mtprops'
make: *** [all] Error 1
```

**Comment by mr-ice** [comment]
This is now fixed, assemble checks that the output directory exists and creates it without errors.
